# image: node:latest

# stages:
#   - lint
#   - test

# eslint:
#   stage: lint
#   script:
#     - npm install
#     - npx eslint --fix .
create_file:
  image: alpine
  script:
   - echo "Building ..."
   - mkdir build
   - touch build/somefile.txt